app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
asian_request_api:
    resource: "@AsianRequestApiBundle/Controller/"
    type:     annotation
    prefix:   api/

asian_user:
    resource: "@AsianUserBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"