services:
#    asian_user.example:
#        class: Asian\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    asian_user.registration:
        class: Asian\UserBundle\EventListener\RegistrationListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }
    asian_user.login:
        class: Asian\UserBundle\EventListener\LoginListener
        arguments: ['@session' ,'@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }
    asian_user.session:
        class: Asian\UserBundle\Model\CustomerSession
        factory: ['Asian\UserBundle\Model\CustomerSession', getInstance]
        arguments: ['@session', '@doctrine.orm.entity_manager']