<?php

namespace Asian\UserBundle\Repository;

/**
 * ApiUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiUserRepository extends \Doctrine\ORM\EntityRepository
{
	const ID = 1;

	/**
	 * get first element
	 *
	 * @return null|object
	 */
	public function getFirstElement()
	{
		return $this->getEntityManager()->find('AsianUserBundle:ApiUser', self::ID);
	}
}
